language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
before_install:
- cd client
- yarn install
- cd ..
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  skip_cleanup: true
  app:
    production: shielded-sands-32381
  api_key:
    secure: Av1pXxjOAs4Iq99w9oeFzRd6h2yROxACFEPYZ3Pbe6SWGMD2JMxZVAWRUZ7fS7VIVCAVtJw4KpTpJ4f+jpHTlrfRIX4Jp1dCmL/y3+g/nGH/8vaZzEZO8TuLYf/McMFJj287CZl0/x+2mGKRkyU7Rjsk8SoeSFq/g5S7FSbbyFpt6yhnE38TWizMwoIEXEY+I7a/Jn11r02FJZ+5RuZ5t+kI+t5AFscbm7FU0b2z0ofocOUXGuWXBzV+KeL3w5FWThCuayK/XIZF1nGcbDcjGCHQ44ymF0p0Bk40SotW/HJjXdhjL7SpRfY4A41hvTZuc993WfomK8vNlqXr9AXuXyUBwH3qmVZAEBBbN89Tv3kuUM/1TNOZn0LLAGAvEL6hbePEKlWheQ9c9LrEHmgv7GlWLY/KX1TXtiITcKF1UCBO4kaIKCy4uNtxo69SwxtCCPb43aeye2zdyZ67WwowSgJxAShouPjHNR/moix7E+7eBgj4l2YL+SXg5enLtm6U0EHpUil4RKXxmzJTypsxPGT0ZuBkogj3iQgaUbZytULAjhgND5qYGPsVUep+cmMYhen2YOgHSnTBox8Mb2atd1QIDatN0dbgak7lw0s7LHgutdv8p2/xu+YHWK+U0yFkwz8g3Vlfms1HLhUwxhV2JPcxgL+5dCMxik5sz9uKj5k=
