language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
before_install:
- cd client
- yarn install
- cd ..
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  skip_cleanup: true
  app:
    production: shielded-sands-32381
  api_key:
    secure: 0maXMpjMEqifst53N9tJ9TggUgYuoWxOngjAbjOzOMl9gOQpxdAF9YmX45Mv9VR8lu/3PX/AGvkEoas9VjlPB9U+PHG2tdERD9gjWP32Kp18rpSJ9Lv3piTEeehT8wtBYhGxv8pYQVw1r4l/Sfxp/BhT1ffYBfrYbEoK2K/nCAOX8zr4gREpAkwTDVwARLLwn4ZQLcJN3+QU2QFXeFbjerNPOe76piaFa/ejQyZF2EpZzcZVFf71hsHv0Qfst9WbMPKabSoGHKrS9QxNsBAxuP5UPwyHEAuiHXjxycH+o0VMOQaqsoarnvbnxjZpuNAcZLgX7PBEfcuCnZbnjJBE93xqsrhFH+MKqNfNOXfdQjAPuVjOFXnu7YvSTlSlT1u3govJmo7SVdTmW7B4hLyV1jpqymi+FfJsj5LVS9U3XMeS1CGbDOAhHBqZeSgjzv5ezxLEPK3O5O5iFUqQdUT+XXhhIBXUyaQ1opEYjEIk9FH8hQ3G101KAvDEVhp5/OGBVphlGIQ/zrDaKMSug66/67iHAh0G2IznZfAbg4Eens95+AyMqQbE4P0ZsDw/sGeBB6Lh4I+NdkkN7+pkHWqrmA1PRzexFKbKulbwYWGaSSxJLlPTetojmQrDvjXMH2XqTE2TsTNeY3wp2/lzCR1nPpgF3yrfWze5AtPx1g6IwK8=
