version: '3'
services:
  app:
    container_name: docker-node
    restart: always
    build: .
    volumes:
      - ./:/config
    ports:
      - 5500:5500
    environment:
      - NODE_ENV=production
      - WISH_ADMIN_CONFIG_TYPE=${WISH_ADMIN_CONFIG_TYPE}
      - WISH_PROJECT_ID=${WISH_PROJECT_ID}
      - WISH_PRIVATE_KEY_ID=${WISH_PRIVATE_KEY_ID}
      - WISH_PRIVATE_KEY=${WISH_PRIVATE_KEY}
      - WISH_CLIENT_EMAIL=${WISH_CLIENT_EMAIL}
      - WISH_CLIENT_ID=${WISH_CLIENT_ID}
      - WISH_AUTH_URI=${WISH_AUTH_URI}
      - WISH_TOKEN_URI=${WISH_TOKEN_URI}
      - WISH_AUTH_PROVIDER_X509_CERT_URL=${WISH_AUTH_PROVIDER_X509_CERT_URL}
      - WISH_CLIENT_X509_CERT_URL=${WISH_CLIENT_X509_CERT_URL}
