version: '3'
services:
  app:
    container_name: docker-node
    restart: always
    build: .
    volumes:
      - ./:/config
    ports:
      - 5500:5500
    environment:
      - NODE_ENV=production
